package uk.ac.ucl.jsh.Parser;
import uk.ac.ucl.jsh.antlr.CmdLineParser.*;

/**
 * Class that visits ANTLR Generated Abstract Syntax Tree by using the Visitor Pattern generated by ANTLR 
 * and creates the custom Tree Structure with Node elements.
 */
public class BuildCmdTree extends CmdLineParserBaseVisitor<Node> {
    @Override
    /**
     * Visits the compileUnit token from the grammar
     * 
     * @param ctx  ANTLR current parsing context 
     */
    public Node visitCompileUnit(CmdLineParserParser.CompileUnitContext ctx) {
        if (ctx.seq() != null) {
            return visit(ctx.seq());
        }

        return visit(ctx.command());
    }
    
    @Override 
    /**
     * Visits a command token from the grammar
     * 
     * @param ctx  ANTLR current parsing context 
     */
    public Node visitCommand(CmdLineParserParser.CommandContext ctx) { 
        if (ctx.pipe() != null) {
            return visit(ctx.pipe());
        }

        return visit(ctx.call());
    }

    @Override
    /**
     * Visits a pipeBase token from the grammar
     * 
     * @param ctx  ANTLR current parsing context 
     * @return     A pipe node based on the current parsing context
     */
    public Node visitPipeBase(CmdLineParserParser.PipeBaseContext ctx) { 
        return new PipeNode(visit(ctx.call1), visit(ctx.call2));
    }

    @Override 
    /**
     * Visits a pipeRecursive token from the grammar
     * 
     * @param ctx  ANTLR current parsing context 
     * @return     A pipe node based on the current parsing context
     */
    public Node visitPipeRecursive(CmdLineParserParser.PipeRecursiveContext ctx) { 
        return new PipeNode(visit(ctx.pipe()), visit(ctx.call()));
    }

    @Override 
    /**
     * Visits a SeqRecursive token from the grammar
     * 
     * @param ctx  ANTLR current parsing context 
     * @return     A seq node based on the current parsing context
     */
    public Node visitSeqRecursive(CmdLineParserParser.SeqRecursiveContext ctx) { 
        return new SeqNode(visit(ctx.seq()), visit(ctx.command()));
    }

    @Override 
    /**
     * Visits a seqBase token from the grammar
     * 
     * @param ctx  ANTLR current parsing context 
     * @return     A seq node based on the current parsing context
     */
    public Node visitSeqBase(CmdLineParserParser.SeqBaseContext ctx) { 
        return new SeqNode(visit(ctx.cmd1), visit(ctx.cmd2));
    }

    @Override
    /**
     * Visits a call token from the grammar
     * 
     * @param ctx  ANTLR current parsing context 
     * @return     A call node based on the current parsing context
     */
    public Node visitCall(CmdLineParserParser.CallContext ctx) {
        return new CallNode(ctx.getText());
    }
}
